openapi: "3.0.0"
info:
  title: Event Manager API
  description: API for managing events, bookings, and digital tickets.
  version: "1.1.0"
  contact:
    name: "Event Manager Admin"
servers:
  - url: http://localhost:5000
    description: Local Development Server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  # --- AUTHENTICATION ---
  /api/auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  example: "Arun Kumar"
                email:
                  type: string
                  format: email
                  example: "arun@test.com"
                password:
                  type: string
                  format: password
                  example: "password123"
      responses:
        '201':
          description: User created successfully
        '400':
          description: User already exists
  /api/auth/login:
    post:
      summary: Login user
      tags:
        - Authentication
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "admin@test.com"
                password:
                  type: string
                  format: password
                  example: "password123"
      responses:
        '200':
          description: Successful login (returns Token)
        '401':
          description: Invalid credentials

  # --- EVENTS ---
  /api/events:
    get:
      summary: Get all events
      tags:
        - Events
      security: []
      responses:
        '200':
          description: List of all events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
    post:
      summary: Create an event (Admin Only)
      tags:
        - Events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventInput'
      responses:
        '201':
          description: Event created successfully
        '401':
          description: Unauthorized (Admin access required)

  /api/events/{id}:
    get:
      summary: Get single event details
      tags:
        - Events
      security: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The event ID
      responses:
        '200':
          description: Event details found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Event not found
    
    put:
      summary: Update an event (Admin Only)
      tags:
        - Events
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The event ID to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventInput'
      responses:
        '200':
          description: Event updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Event not found
        '401':
          description: Unauthorized

    delete:
      summary: Delete an event (Admin Only)
      tags:
        - Events
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The event ID to delete
      responses:
        '200':
          description: Event deleted successfully
        '404':
          description: Event not found

  # --- BOOKINGS ---
  /api/bookings:
    post:
      summary: Book tickets
      tags:
        - Bookings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - eventId
                - count
              properties:
                eventId:
                  type: string
                  example: "654321..."
                count:
                  type: integer
                  minimum: 1
                  example: 2
      responses:
        '201':
          description: Booking successful
        '400':
          description: Not enough tickets or invalid data

  /api/bookings/mybookings:
    get:
      summary: Get current user's bookings
      tags:
        - Bookings
      responses:
        '200':
          description: List of user bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'

  /api/bookings/verify/{ticketId}:
    get:
      summary: Verify ticket status (Public)
      tags:
        - Bookings
      security: []
      parameters:
        - in: path
          name: ticketId
          schema:
            type: string
          required: true
          description: Unique Ticket ID (e.g. TKT-123...)
      responses:
        '200':
          description: Valid ticket details
        '404':
          description: Ticket not found

# --- SCHEMAS ---
components:
  schemas:
    Event:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        date:
          type: string
          format: date-time
        location:
          type: string
        price:
          type: number
          description: Price in Rupees (Rs.)
        totalTickets:
          type: integer
        availableTickets:
          type: integer
        image:
          type: string
        description:
          type: string
    EventInput:
      type: object
      properties:
        title:
          type: string
          example: "Music Concert 2026"
        date:
          type: string
          format: date-time
          example: "2026-01-01T18:00:00Z"
        location:
          type: string
          example: "Nehru Stadium, Chennai"
        price:
          type: number
          example: 499
        totalTickets:
          type: integer
          example: 100
        image:
          type: string
          example: "https://placehold.co/600x400"
        description:
           type: string
           example: "An amazing live music experience."
    Booking:
      type: object
      properties:
        _id:
          type: string
        user:
          type: string
        event:
          $ref: '#/components/schemas/Event'
        ticketId:
          type: string
        count:
          type: integer
        totalCost:
          type: number